### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by ifrahur** [cyberboysumanjay/Inshorts-News-API#1]

**Comment by cyberboysumanjay** [comment]
What's the issue you're facing?

**Comment by ifrahur** [comment]
https://inshortsapi.herokuapp.com/news?category=science

the above link is giving There's nothing here, yet.

**Comment by cyberboysumanjay** [comment]
It seems that my free hours has been expired. 
You can deploy your own version on heroku by clicking on **Deploy to Heroku** button given in the README

**Comment by ifrahur** [comment]
ooh okay.. thanks a lot.. your API was very helpful..

**Comment by cyberboysumanjay** [comment]
Glad you liked it 😊
