### ISSUE TITLE
It is not working 

### ISSUE THREAD

**Issue by pg07codes** [cyberboysumanjay/Inshorts-News-API#2]
the deployment is not working. 
If it is not deployed as of now, please do change the status of api to NOT AVAILABLE.

**Comment by cyberboysumanjay** [comment]
The API is working fine and I'm using it to run https://t.me/news_inshorts

You need to fork this and deploy your own version of the API

**Comment by pg07codes** [comment]
It will be great if you just mention "deploy and use " on it. 
The readme got me into thinking if it is already deployed at https://inshortsapi.herokuapp.com.

Thanks anyways.
