### ISSUE TITLE
Support article id and query with the id?

### ISSUE THREAD

**Issue by leonlee0116** [cyberboysumanjay/Inshorts-News-API#5]
I was making a simple news app and I unable to do bookmark feature without the article id.
Is this possible in the future?

**Comment by cyberboysumanjay** [comment]
I've added id tags for each of the news entity.

`{
      "author": "Ria Kapoor",
      "content": "Punjab Chief Minister Bhagwant Mann has announced to set up judicial commission under the sitting judge of Punjab and Haryana High Court to investigate the killing of Punjabi singer Sidhu Moosewala. Moosewala was shot dead in Punjab's Mansa on Sunday. The singer's father had earlier written to CM Mann saying that his son left forever due to the government's failures. ",
      "date": "30 May 2022,Monday",
      "id": "195c8e5c1cb949368ba6715b8781e408",
      "imageUrl": "https://static.inshorts.com/inshorts/images/v1/variants/jpg/m/2022/05_may/30_mon/img_1653905273672_749.jpg?",
      "readMoreUrl": "https://twitter.com/ANI/status/1531206377682907137?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts ",
      "time": "03:42 pm",
      "title": "Punjab govt to set up judicial commission to probe Sidhu Moosewala’s killing",
      "url": "https://www.inshorts.com/en/news/punjab-govt-to-set-up-judicial-commission-to-probe-sidhu-moosewalas-killing-1653905540958"
    }`

This is how the unit news response looks like. I think you can implement what you wanted from this. 
Regarding the search feature you can store the news in local (shared pref or whatever else you like) and use this id key to fetch it.

Good Luck 👍🏻 
Feel free to reopen this issue in case you want more help.
